// THIS FILE IS AUTO-GENERATED by scripts/update-voice-docs.js.
// Do not edit this file manually.

export const AMAZON_POLLY_ALL_VOICES: Record<string, any> = {
  ["aditi"]: {
      "voice": {
        "name": "Aditi"
      }
    },
  ["adriano"]: {
      "voice": {
        "name": "Adriano"
      }
    },
  ["alba"]: {
      "voice": {
        "name": "Alba"
      }
    },
  ["amy"]: {
      "voice": {
        "name": "Amy"
      }
    },
  ["andres"]: {
      "voice": {
        "name": "Andres"
      }
    },
  ["aria"]: {
      "voice": {
        "name": "Aria"
      }
    },
  ["arlet"]: {
      "voice": {
        "name": "Arlet"
      }
    },
  ["arthur"]: {
      "voice": {
        "name": "Arthur"
      }
    },
  ["astrid"]: {
      "voice": {
        "name": "Astrid"
      }
    },
  ["ayanda"]: {
      "voice": {
        "name": "Ayanda"
      }
    },
  ["bianca"]: {
      "voice": {
        "name": "Bianca"
      }
    },
  ["brian"]: {
      "voice": {
        "name": "Brian"
      }
    },
  ["burcu"]: {
      "voice": {
        "name": "Burcu"
      }
    },
  ["camila"]: {
      "voice": {
        "name": "Camila"
      }
    },
  ["carla"]: {
      "voice": {
        "name": "Carla"
      }
    },
  ["carmen"]: {
      "voice": {
        "name": "Carmen"
      }
    },
  ["celine"]: {
      "voice": {
        "name": "Celine"
      }
    },
  ["chantal"]: {
      "voice": {
        "name": "Chantal"
      }
    },
  ["conchita"]: {
      "voice": {
        "name": "Conchita"
      }
    },
  ["cristiano"]: {
      "voice": {
        "name": "Cristiano"
      }
    },
  ["daniel"]: {
      "voice": {
        "name": "Daniel"
      }
    },
  ["danielle"]: {
      "voice": {
        "name": "Danielle"
      }
    },
  ["dora"]: {
      "voice": {
        "name": "Dora"
      }
    },
  ["elin"]: {
      "voice": {
        "name": "Elin"
      }
    },
  ["emma"]: {
      "voice": {
        "name": "Emma"
      }
    },
  ["enrique"]: {
      "voice": {
        "name": "Enrique"
      }
    },
  ["ewa"]: {
      "voice": {
        "name": "Ewa"
      }
    },
  ["filiz"]: {
      "voice": {
        "name": "Filiz"
      }
    },
  ["gabrielle"]: {
      "voice": {
        "name": "Gabrielle"
      }
    },
  ["geraint"]: {
      "voice": {
        "name": "Geraint"
      }
    },
  ["giorgio"]: {
      "voice": {
        "name": "Giorgio"
      }
    },
  ["gregory"]: {
      "voice": {
        "name": "Gregory"
      }
    },
  ["gwyneth"]: {
      "voice": {
        "name": "Gwyneth"
      }
    },
  ["hala"]: {
      "voice": {
        "name": "Hala"
      }
    },
  ["hannah"]: {
      "voice": {
        "name": "Hannah"
      }
    },
  ["hans"]: {
      "voice": {
        "name": "Hans"
      }
    },
  ["hiujin"]: {
      "voice": {
        "name": "Hiujin"
      }
    },
  ["ida"]: {
      "voice": {
        "name": "Ida"
      }
    },
  ["ines"]: {
      "voice": {
        "name": "Ines"
      }
    },
  ["isabelle"]: {
      "voice": {
        "name": "Isabelle"
      }
    },
  ["ivy"]: {
      "voice": {
        "name": "Ivy"
      }
    },
  ["jacek"]: {
      "voice": {
        "name": "Jacek"
      }
    },
  ["jan"]: {
      "voice": {
        "name": "Jan"
      }
    },
  ["jasmine"]: {
      "voice": {
        "name": "Jasmine"
      }
    },
  ["jihye"]: {
      "voice": {
        "name": "Jihye"
      }
    },
  ["jitka"]: {
      "voice": {
        "name": "Jitka"
      }
    },
  ["joanna"]: {
      "voice": {
        "name": "Joanna"
      }
    },
  ["joey"]: {
      "voice": {
        "name": "Joey"
      }
    },
  ["justin"]: {
      "voice": {
        "name": "Justin"
      }
    },
  ["kajal"]: {
      "voice": {
        "name": "Kajal"
      }
    },
  ["karl"]: {
      "voice": {
        "name": "Karl"
      }
    },
  ["kazuha"]: {
      "voice": {
        "name": "Kazuha"
      }
    },
  ["kendra"]: {
      "voice": {
        "name": "Kendra"
      }
    },
  ["kevin"]: {
      "voice": {
        "name": "Kevin"
      }
    },
  ["kimberly"]: {
      "voice": {
        "name": "Kimberly"
      }
    },
  ["laura"]: {
      "voice": {
        "name": "Laura"
      }
    },
  ["lea"]: {
      "voice": {
        "name": "Lea"
      }
    },
  ["liam"]: {
      "voice": {
        "name": "Liam"
      }
    },
  ["lisa"]: {
      "voice": {
        "name": "Lisa"
      }
    },
  ["liv"]: {
      "voice": {
        "name": "Liv"
      }
    },
  ["lotte"]: {
      "voice": {
        "name": "Lotte"
      }
    },
  ["lucia"]: {
      "voice": {
        "name": "Lucia"
      }
    },
  ["lupe"]: {
      "voice": {
        "name": "Lupe"
      }
    },
  ["mads"]: {
      "voice": {
        "name": "Mads"
      }
    },
  ["maja"]: {
      "voice": {
        "name": "Maja"
      }
    },
  ["marlene"]: {
      "voice": {
        "name": "Marlene"
      }
    },
  ["mathieu"]: {
      "voice": {
        "name": "Mathieu"
      }
    },
  ["matthew"]: {
      "voice": {
        "name": "Matthew"
      }
    },
  ["maxim"]: {
      "voice": {
        "name": "Maxim"
      }
    },
  ["mia"]: {
      "voice": {
        "name": "Mia"
      }
    },
  ["miguel"]: {
      "voice": {
        "name": "Miguel"
      }
    },
  ["mizuki"]: {
      "voice": {
        "name": "Mizuki"
      }
    },
  ["naja"]: {
      "voice": {
        "name": "Naja"
      }
    },
  ["niamh"]: {
      "voice": {
        "name": "Niamh"
      }
    },
  ["nicole"]: {
      "voice": {
        "name": "Nicole"
      }
    },
  ["ola"]: {
      "voice": {
        "name": "Ola"
      }
    },
  ["olivia"]: {
      "voice": {
        "name": "Olivia"
      }
    },
  ["patrick"]: {
      "voice": {
        "name": "Patrick"
      }
    },
  ["pedro"]: {
      "voice": {
        "name": "Pedro"
      }
    },
  ["penelope"]: {
      "voice": {
        "name": "Penelope"
      }
    },
  ["raul"]: {
      "voice": {
        "name": "Raul"
      }
    },
  ["raveena"]: {
      "voice": {
        "name": "Raveena"
      }
    },
  ["remi"]: {
      "voice": {
        "name": "Remi"
      }
    },
  ["ricardo"]: {
      "voice": {
        "name": "Ricardo"
      }
    },
  ["ruben"]: {
      "voice": {
        "name": "Ruben"
      }
    },
  ["russell"]: {
      "voice": {
        "name": "Russell"
      }
    },
  ["ruth"]: {
      "voice": {
        "name": "Ruth"
      }
    },
  ["sabrina"]: {
      "voice": {
        "name": "Sabrina"
      }
    },
  ["salli"]: {
      "voice": {
        "name": "Salli"
      }
    },
  ["seoyeon"]: {
      "voice": {
        "name": "Seoyeon"
      }
    },
  ["sergio"]: {
      "voice": {
        "name": "Sergio"
      }
    },
  ["sofie"]: {
      "voice": {
        "name": "Sofie"
      }
    },
  ["stephen"]: {
      "voice": {
        "name": "Stephen"
      }
    },
  ["suvi"]: {
      "voice": {
        "name": "Suvi"
      }
    },
  ["takumi"]: {
      "voice": {
        "name": "Takumi"
      }
    },
  ["tatyana"]: {
      "voice": {
        "name": "Tatyana"
      }
    },
  ["thiago"]: {
      "voice": {
        "name": "Thiago"
      }
    },
  ["tomoko"]: {
      "voice": {
        "name": "Tomoko"
      }
    },
  ["vicki"]: {
      "voice": {
        "name": "Vicki"
      }
    },
  ["vitoria"]: {
      "voice": {
        "name": "Vitoria"
      }
    },
  ["zayd"]: {
      "voice": {
        "name": "Zayd"
      }
    },
  ["zeina"]: {
      "voice": {
        "name": "Zeina"
      }
    },
  ["zhiyu"]: {
      "voice": {
        "name": "Zhiyu"
      }
    },
};

export const AMAZON_POLLY_STANDARD_VOICES: Record<string, any> = {
  ["aditi"]: {
      "voice": {
        "name": "Aditi"
      }
    },
  ["amy"]: {
      "voice": {
        "name": "Amy"
      }
    },
  ["astrid"]: {
      "voice": {
        "name": "Astrid"
      }
    },
  ["bianca"]: {
      "voice": {
        "name": "Bianca"
      }
    },
  ["brian"]: {
      "voice": {
        "name": "Brian"
      }
    },
  ["camila"]: {
      "voice": {
        "name": "Camila"
      }
    },
  ["carla"]: {
      "voice": {
        "name": "Carla"
      }
    },
  ["carmen"]: {
      "voice": {
        "name": "Carmen"
      }
    },
  ["celine"]: {
      "voice": {
        "name": "Celine"
      }
    },
  ["chantal"]: {
      "voice": {
        "name": "Chantal"
      }
    },
  ["conchita"]: {
      "voice": {
        "name": "Conchita"
      }
    },
  ["cristiano"]: {
      "voice": {
        "name": "Cristiano"
      }
    },
  ["dora"]: {
      "voice": {
        "name": "Dora"
      }
    },
  ["emma"]: {
      "voice": {
        "name": "Emma"
      }
    },
  ["enrique"]: {
      "voice": {
        "name": "Enrique"
      }
    },
  ["ewa"]: {
      "voice": {
        "name": "Ewa"
      }
    },
  ["filiz"]: {
      "voice": {
        "name": "Filiz"
      }
    },
  ["geraint"]: {
      "voice": {
        "name": "Geraint"
      }
    },
  ["giorgio"]: {
      "voice": {
        "name": "Giorgio"
      }
    },
  ["gwyneth"]: {
      "voice": {
        "name": "Gwyneth"
      }
    },
  ["hans"]: {
      "voice": {
        "name": "Hans"
      }
    },
  ["ines"]: {
      "voice": {
        "name": "Ines"
      }
    },
  ["ivy"]: {
      "voice": {
        "name": "Ivy"
      }
    },
  ["jacek"]: {
      "voice": {
        "name": "Jacek"
      }
    },
  ["jan"]: {
      "voice": {
        "name": "Jan"
      }
    },
  ["joanna"]: {
      "voice": {
        "name": "Joanna"
      }
    },
  ["joey"]: {
      "voice": {
        "name": "Joey"
      }
    },
  ["justin"]: {
      "voice": {
        "name": "Justin"
      }
    },
  ["karl"]: {
      "voice": {
        "name": "Karl"
      }
    },
  ["kendra"]: {
      "voice": {
        "name": "Kendra"
      }
    },
  ["kimberly"]: {
      "voice": {
        "name": "Kimberly"
      }
    },
  ["lea"]: {
      "voice": {
        "name": "Lea"
      }
    },
  ["liv"]: {
      "voice": {
        "name": "Liv"
      }
    },
  ["lotte"]: {
      "voice": {
        "name": "Lotte"
      }
    },
  ["lucia"]: {
      "voice": {
        "name": "Lucia"
      }
    },
  ["lupe"]: {
      "voice": {
        "name": "Lupe"
      }
    },
  ["mads"]: {
      "voice": {
        "name": "Mads"
      }
    },
  ["maja"]: {
      "voice": {
        "name": "Maja"
      }
    },
  ["marlene"]: {
      "voice": {
        "name": "Marlene"
      }
    },
  ["mathieu"]: {
      "voice": {
        "name": "Mathieu"
      }
    },
  ["matthew"]: {
      "voice": {
        "name": "Matthew"
      }
    },
  ["maxim"]: {
      "voice": {
        "name": "Maxim"
      }
    },
  ["mia"]: {
      "voice": {
        "name": "Mia"
      }
    },
  ["miguel"]: {
      "voice": {
        "name": "Miguel"
      }
    },
  ["mizuki"]: {
      "voice": {
        "name": "Mizuki"
      }
    },
  ["naja"]: {
      "voice": {
        "name": "Naja"
      }
    },
  ["nicole"]: {
      "voice": {
        "name": "Nicole"
      }
    },
  ["penelope"]: {
      "voice": {
        "name": "Penelope"
      }
    },
  ["raveena"]: {
      "voice": {
        "name": "Raveena"
      }
    },
  ["ricardo"]: {
      "voice": {
        "name": "Ricardo"
      }
    },
  ["ruben"]: {
      "voice": {
        "name": "Ruben"
      }
    },
  ["russell"]: {
      "voice": {
        "name": "Russell"
      }
    },
  ["salli"]: {
      "voice": {
        "name": "Salli"
      }
    },
  ["seoyeon"]: {
      "voice": {
        "name": "Seoyeon"
      }
    },
  ["takumi"]: {
      "voice": {
        "name": "Takumi"
      }
    },
  ["tatyana"]: {
      "voice": {
        "name": "Tatyana"
      }
    },
  ["vicki"]: {
      "voice": {
        "name": "Vicki"
      }
    },
  ["vitoria"]: {
      "voice": {
        "name": "Vitoria"
      }
    },
  ["zeina"]: {
      "voice": {
        "name": "Zeina"
      }
    },
  ["zhiyu"]: {
      "voice": {
        "name": "Zhiyu"
      }
    },
};

export const AMAZON_POLLY_NEURAL_VOICES: Record<string, any> = {
  ["adriano"]: {
      "voice": {
        "name": "Adriano"
      }
    },
  ["amy"]: {
      "voice": {
        "name": "Amy"
      }
    },
  ["andres"]: {
      "voice": {
        "name": "Andres"
      }
    },
  ["aria"]: {
      "voice": {
        "name": "Aria"
      }
    },
  ["arlet"]: {
      "voice": {
        "name": "Arlet"
      }
    },
  ["arthur"]: {
      "voice": {
        "name": "Arthur"
      }
    },
  ["ayanda"]: {
      "voice": {
        "name": "Ayanda"
      }
    },
  ["bianca"]: {
      "voice": {
        "name": "Bianca"
      }
    },
  ["brian"]: {
      "voice": {
        "name": "Brian"
      }
    },
  ["burcu"]: {
      "voice": {
        "name": "Burcu"
      }
    },
  ["camila"]: {
      "voice": {
        "name": "Camila"
      }
    },
  ["daniel"]: {
      "voice": {
        "name": "Daniel"
      }
    },
  ["danielle"]: {
      "voice": {
        "name": "Danielle"
      }
    },
  ["elin"]: {
      "voice": {
        "name": "Elin"
      }
    },
  ["emma"]: {
      "voice": {
        "name": "Emma"
      }
    },
  ["gabrielle"]: {
      "voice": {
        "name": "Gabrielle"
      }
    },
  ["gregory"]: {
      "voice": {
        "name": "Gregory"
      }
    },
  ["hala"]: {
      "voice": {
        "name": "Hala"
      }
    },
  ["hannah"]: {
      "voice": {
        "name": "Hannah"
      }
    },
  ["hiujin"]: {
      "voice": {
        "name": "Hiujin"
      }
    },
  ["ida"]: {
      "voice": {
        "name": "Ida"
      }
    },
  ["ines"]: {
      "voice": {
        "name": "Ines"
      }
    },
  ["isabelle"]: {
      "voice": {
        "name": "Isabelle"
      }
    },
  ["ivy"]: {
      "voice": {
        "name": "Ivy"
      }
    },
  ["jasmine"]: {
      "voice": {
        "name": "Jasmine"
      }
    },
  ["jihye"]: {
      "voice": {
        "name": "Jihye"
      }
    },
  ["jitka"]: {
      "voice": {
        "name": "Jitka"
      }
    },
  ["joanna"]: {
      "voice": {
        "name": "Joanna"
      }
    },
  ["joey"]: {
      "voice": {
        "name": "Joey"
      }
    },
  ["justin"]: {
      "voice": {
        "name": "Justin"
      }
    },
  ["kajal"]: {
      "voice": {
        "name": "Kajal"
      }
    },
  ["kazuha"]: {
      "voice": {
        "name": "Kazuha"
      }
    },
  ["kendra"]: {
      "voice": {
        "name": "Kendra"
      }
    },
  ["kevin"]: {
      "voice": {
        "name": "Kevin"
      }
    },
  ["kimberly"]: {
      "voice": {
        "name": "Kimberly"
      }
    },
  ["laura"]: {
      "voice": {
        "name": "Laura"
      }
    },
  ["lea"]: {
      "voice": {
        "name": "Lea"
      }
    },
  ["liam"]: {
      "voice": {
        "name": "Liam"
      }
    },
  ["lisa"]: {
      "voice": {
        "name": "Lisa"
      }
    },
  ["lucia"]: {
      "voice": {
        "name": "Lucia"
      }
    },
  ["lupe"]: {
      "voice": {
        "name": "Lupe"
      }
    },
  ["matthew"]: {
      "voice": {
        "name": "Matthew"
      }
    },
  ["mia"]: {
      "voice": {
        "name": "Mia"
      }
    },
  ["niamh"]: {
      "voice": {
        "name": "Niamh"
      }
    },
  ["ola"]: {
      "voice": {
        "name": "Ola"
      }
    },
  ["olivia"]: {
      "voice": {
        "name": "Olivia"
      }
    },
  ["pedro"]: {
      "voice": {
        "name": "Pedro"
      }
    },
  ["remi"]: {
      "voice": {
        "name": "Remi"
      }
    },
  ["ruth"]: {
      "voice": {
        "name": "Ruth"
      }
    },
  ["sabrina"]: {
      "voice": {
        "name": "Sabrina"
      }
    },
  ["salli"]: {
      "voice": {
        "name": "Salli"
      }
    },
  ["seoyeon"]: {
      "voice": {
        "name": "Seoyeon"
      }
    },
  ["sergio"]: {
      "voice": {
        "name": "Sergio"
      }
    },
  ["sofie"]: {
      "voice": {
        "name": "Sofie"
      }
    },
  ["stephen"]: {
      "voice": {
        "name": "Stephen"
      }
    },
  ["suvi"]: {
      "voice": {
        "name": "Suvi"
      }
    },
  ["takumi"]: {
      "voice": {
        "name": "Takumi"
      }
    },
  ["thiago"]: {
      "voice": {
        "name": "Thiago"
      }
    },
  ["tomoko"]: {
      "voice": {
        "name": "Tomoko"
      }
    },
  ["vicki"]: {
      "voice": {
        "name": "Vicki"
      }
    },
  ["vitoria"]: {
      "voice": {
        "name": "Vitoria"
      }
    },
  ["zayd"]: {
      "voice": {
        "name": "Zayd"
      }
    },
  ["zhiyu"]: {
      "voice": {
        "name": "Zhiyu"
      }
    },
};

export const AMAZON_POLLY_GENERATIVE_VOICES: Record<string, any> = {
  ["amy"]: {
      "voice": {
        "name": "Amy"
      }
    },
  ["andres"]: {
      "voice": {
        "name": "Andres"
      }
    },
  ["ayanda"]: {
      "voice": {
        "name": "Ayanda"
      }
    },
  ["bianca"]: {
      "voice": {
        "name": "Bianca"
      }
    },
  ["celine"]: {
      "voice": {
        "name": "Celine"
      }
    },
  ["daniel"]: {
      "voice": {
        "name": "Daniel"
      }
    },
  ["danielle"]: {
      "voice": {
        "name": "Danielle"
      }
    },
  ["ewa"]: {
      "voice": {
        "name": "Ewa"
      }
    },
  ["gabrielle"]: {
      "voice": {
        "name": "Gabrielle"
      }
    },
  ["isabelle"]: {
      "voice": {
        "name": "Isabelle"
      }
    },
  ["joanna"]: {
      "voice": {
        "name": "Joanna"
      }
    },
  ["kajal"]: {
      "voice": {
        "name": "Kajal"
      }
    },
  ["lea"]: {
      "voice": {
        "name": "Lea"
      }
    },
  ["liam"]: {
      "voice": {
        "name": "Liam"
      }
    },
  ["lucia"]: {
      "voice": {
        "name": "Lucia"
      }
    },
  ["lupe"]: {
      "voice": {
        "name": "Lupe"
      }
    },
  ["matthew"]: {
      "voice": {
        "name": "Matthew"
      }
    },
  ["mia"]: {
      "voice": {
        "name": "Mia"
      }
    },
  ["ola"]: {
      "voice": {
        "name": "Ola"
      }
    },
  ["olivia"]: {
      "voice": {
        "name": "Olivia"
      }
    },
  ["pedro"]: {
      "voice": {
        "name": "Pedro"
      }
    },
  ["remi"]: {
      "voice": {
        "name": "Remi"
      }
    },
  ["ruth"]: {
      "voice": {
        "name": "Ruth"
      }
    },
  ["salli"]: {
      "voice": {
        "name": "Salli"
      }
    },
  ["sergio"]: {
      "voice": {
        "name": "Sergio"
      }
    },
  ["stephen"]: {
      "voice": {
        "name": "Stephen"
      }
    },
  ["vicki"]: {
      "voice": {
        "name": "Vicki"
      }
    },
};

