// THIS FILE IS AUTO-GENERATED by scripts/update-voice-data.js.
// Do not edit this file manually.

export const IBM_WATSON_TTS_VOICES: Record<string, any> = {
  ["de-de_birgitv2voice"]: {
      "voice": {
        "name": "de-DE_BirgitV2Voice"
      }
    },
  ["de-de_birgitv3voice"]: {
      "voice": {
        "name": "de-DE_BirgitV3Voice"
      }
    },
  ["de-de_birgitvoice"]: {
      "voice": {
        "name": "de-DE_BirgitVoice"
      }
    },
  ["de-de_dieterv2voice"]: {
      "voice": {
        "name": "de-DE_DieterV2Voice"
      }
    },
  ["de-de_dieterv3voice"]: {
      "voice": {
        "name": "de-DE_DieterV3Voice"
      }
    },
  ["de-de_dietervoice"]: {
      "voice": {
        "name": "de-DE_DieterVoice"
      }
    },
  ["de-de_erikav3voice"]: {
      "voice": {
        "name": "de-DE_ErikaV3Voice"
      }
    },
  ["en-au_heidiexpressive"]: {
      "voice": {
        "name": "en-AU_HeidiExpressive"
      }
    },
  ["en-au_jackexpressive"]: {
      "voice": {
        "name": "en-AU_JackExpressive"
      }
    },
  ["en-ca_hannahnatural"]: {
      "voice": {
        "name": "en-CA_HannahNatural"
      }
    },
  ["en-gb_charlottev3voice"]: {
      "voice": {
        "name": "en-GB_CharlotteV3Voice"
      }
    },
  ["en-gb_chloenatural"]: {
      "voice": {
        "name": "en-GB_ChloeNatural"
      }
    },
  ["en-gb_georgeexpressive"]: {
      "voice": {
        "name": "en-GB_GeorgeExpressive"
      }
    },
  ["en-gb_georgenatural"]: {
      "voice": {
        "name": "en-GB_GeorgeNatural"
      }
    },
  ["en-gb_katev3voice"]: {
      "voice": {
        "name": "en-GB_KateV3Voice"
      }
    },
  ["en-gb_katevoice"]: {
      "voice": {
        "name": "en-GB_KateVoice"
      }
    },
  ["en-us_allisonexpressive"]: {
      "voice": {
        "name": "en-US_AllisonExpressive"
      }
    },
  ["en-us_allisonv2voice"]: {
      "voice": {
        "name": "en-US_AllisonV2Voice"
      }
    },
  ["en-us_allisonv3voice"]: {
      "voice": {
        "name": "en-US_AllisonV3Voice"
      }
    },
  ["en-us_allisonvoice"]: {
      "voice": {
        "name": "en-US_AllisonVoice"
      }
    },
  ["en-us_ellienatural"]: {
      "voice": {
        "name": "en-US_EllieNatural"
      }
    },
  ["en-us_emilyv3voice"]: {
      "voice": {
        "name": "en-US_EmilyV3Voice"
      }
    },
  ["en-us_emmaexpressive"]: {
      "voice": {
        "name": "en-US_EmmaExpressive"
      }
    },
  ["en-us_emmanatural"]: {
      "voice": {
        "name": "en-US_EmmaNatural"
      }
    },
  ["en-us_ethannatural"]: {
      "voice": {
        "name": "en-US_EthanNatural"
      }
    },
  ["en-us_henryv3voice"]: {
      "voice": {
        "name": "en-US_HenryV3Voice"
      }
    },
  ["en-us_jacksonnatural"]: {
      "voice": {
        "name": "en-US_JacksonNatural"
      }
    },
  ["en-us_kevinv3voice"]: {
      "voice": {
        "name": "en-US_KevinV3Voice"
      }
    },
  ["en-us_lisaexpressive"]: {
      "voice": {
        "name": "en-US_LisaExpressive"
      }
    },
  ["en-us_lisav2voice"]: {
      "voice": {
        "name": "en-US_LisaV2Voice"
      }
    },
  ["en-us_lisav3voice"]: {
      "voice": {
        "name": "en-US_LisaV3Voice"
      }
    },
  ["en-us_lisavoice"]: {
      "voice": {
        "name": "en-US_LisaVoice"
      }
    },
  ["en-us_michaelexpressive"]: {
      "voice": {
        "name": "en-US_MichaelExpressive"
      }
    },
  ["en-us_michaelv2voice"]: {
      "voice": {
        "name": "en-US_MichaelV2Voice"
      }
    },
  ["en-us_michaelv3voice"]: {
      "voice": {
        "name": "en-US_MichaelV3Voice"
      }
    },
  ["en-us_michaelvoice"]: {
      "voice": {
        "name": "en-US_MichaelVoice"
      }
    },
  ["en-us_oliviav3voice"]: {
      "voice": {
        "name": "en-US_OliviaV3Voice"
      }
    },
  ["en-us_victorianatural"]: {
      "voice": {
        "name": "en-US_VictoriaNatural"
      }
    },
  ["es-es_enriquev3voice"]: {
      "voice": {
        "name": "es-ES_EnriqueV3Voice"
      }
    },
  ["es-es_enriquevoice"]: {
      "voice": {
        "name": "es-ES_EnriqueVoice"
      }
    },
  ["es-es_laurav3voice"]: {
      "voice": {
        "name": "es-ES_LauraV3Voice"
      }
    },
  ["es-es_lauravoice"]: {
      "voice": {
        "name": "es-ES_LauraVoice"
      }
    },
  ["es-la_danielaexpressive"]: {
      "voice": {
        "name": "es-LA_DanielaExpressive"
      }
    },
  ["es-la_sofiav3voice"]: {
      "voice": {
        "name": "es-LA_SofiaV3Voice"
      }
    },
  ["es-la_sofiavoice"]: {
      "voice": {
        "name": "es-LA_SofiaVoice"
      }
    },
  ["es-us_sofiav3voice"]: {
      "voice": {
        "name": "es-US_SofiaV3Voice"
      }
    },
  ["es-us_sofiavoice"]: {
      "voice": {
        "name": "es-US_SofiaVoice"
      }
    },
  ["fr-ca_louisev3voice"]: {
      "voice": {
        "name": "fr-CA_LouiseV3Voice"
      }
    },
  ["fr-fr_nicolasv3voice"]: {
      "voice": {
        "name": "fr-FR_NicolasV3Voice"
      }
    },
  ["fr-fr_reneev3voice"]: {
      "voice": {
        "name": "fr-FR_ReneeV3Voice"
      }
    },
  ["fr-fr_reneevoice"]: {
      "voice": {
        "name": "fr-FR_ReneeVoice"
      }
    },
  ["it-it_francescav2voice"]: {
      "voice": {
        "name": "it-IT_FrancescaV2Voice"
      }
    },
  ["it-it_francescav3voice"]: {
      "voice": {
        "name": "it-IT_FrancescaV3Voice"
      }
    },
  ["it-it_francescavoice"]: {
      "voice": {
        "name": "it-IT_FrancescaVoice"
      }
    },
  ["ja-jp_emiv3voice"]: {
      "voice": {
        "name": "ja-JP_EmiV3Voice"
      }
    },
  ["ja-jp_emivoice"]: {
      "voice": {
        "name": "ja-JP_EmiVoice"
      }
    },
  ["ko-kr_jinv3voice"]: {
      "voice": {
        "name": "ko-KR_JinV3Voice"
      }
    },
  ["nl-nl_merelv3voice"]: {
      "voice": {
        "name": "nl-NL_MerelV3Voice"
      }
    },
  ["pt-br_isabelav3voice"]: {
      "voice": {
        "name": "pt-BR_IsabelaV3Voice"
      }
    },
  ["pt-br_isabelavoice"]: {
      "voice": {
        "name": "pt-BR_IsabelaVoice"
      }
    },
  ["pt-br_lucasexpressive"]: {
      "voice": {
        "name": "pt-BR_LucasExpressive"
      }
    },
};

