// THIS FILE IS AUTO-GENERATED by scripts/update-voice-data.js.
// Do not edit this file manually.

export const MICROSOFT_AZURE_TTS_VOICES: Record<string, any> = {
  ['af-za-adrineural']: {
    voice: {
      name: 'af-ZA-AdriNeural',
    },
  },
  ['af-za-willemneural']: {
    voice: {
      name: 'af-ZA-WillemNeural',
    },
  },
  ['am-et-amehaneural']: {
    voice: {
      name: 'am-ET-AmehaNeural',
    },
  },
  ['am-et-mekdesneural']: {
    voice: {
      name: 'am-ET-MekdesNeural',
    },
  },
  ['ar-ae-fatimaneural']: {
    voice: {
      name: 'ar-AE-FatimaNeural',
    },
  },
  ['ar-ae-hamdanneural']: {
    voice: {
      name: 'ar-AE-HamdanNeural',
    },
  },
  ['ar-bh-alineural']: {
    voice: {
      name: 'ar-BH-AliNeural',
    },
  },
  ['ar-bh-lailaneural']: {
    voice: {
      name: 'ar-BH-LailaNeural',
    },
  },
  ['ar-dz-aminaneural']: {
    voice: {
      name: 'ar-DZ-AminaNeural',
    },
  },
  ['ar-dz-ismaelneural']: {
    voice: {
      name: 'ar-DZ-IsmaelNeural',
    },
  },
  ['ar-eg-salmaneural']: {
    voice: {
      name: 'ar-EG-SalmaNeural',
    },
  },
  ['ar-eg-shakirneural']: {
    voice: {
      name: 'ar-EG-ShakirNeural',
    },
  },
  ['ar-iq-basselneural']: {
    voice: {
      name: 'ar-IQ-BasselNeural',
    },
  },
  ['ar-iq-rananeural']: {
    voice: {
      name: 'ar-IQ-RanaNeural',
    },
  },
  ['ar-jo-sananeural']: {
    voice: {
      name: 'ar-JO-SanaNeural',
    },
  },
  ['ar-jo-taimneural']: {
    voice: {
      name: 'ar-JO-TaimNeural',
    },
  },
  ['ar-kw-fahedneural']: {
    voice: {
      name: 'ar-KW-FahedNeural',
    },
  },
  ['ar-kw-nouraneural']: {
    voice: {
      name: 'ar-KW-NouraNeural',
    },
  },
  ['ar-lb-laylaneural']: {
    voice: {
      name: 'ar-LB-LaylaNeural',
    },
  },
  ['ar-lb-ramineural']: {
    voice: {
      name: 'ar-LB-RamiNeural',
    },
  },
  ['ar-ly-imanneural']: {
    voice: {
      name: 'ar-LY-ImanNeural',
    },
  },
  ['ar-ly-omarneural']: {
    voice: {
      name: 'ar-LY-OmarNeural',
    },
  },
  ['ar-ma-jamalneural']: {
    voice: {
      name: 'ar-MA-JamalNeural',
    },
  },
  ['ar-ma-mounaneural']: {
    voice: {
      name: 'ar-MA-MounaNeural',
    },
  },
  ['ar-om-abdullahneural']: {
    voice: {
      name: 'ar-OM-AbdullahNeural',
    },
  },
  ['ar-om-ayshaneural']: {
    voice: {
      name: 'ar-OM-AyshaNeural',
    },
  },
  ['ar-qa-amalneural']: {
    voice: {
      name: 'ar-QA-AmalNeural',
    },
  },
  ['ar-qa-moazneural']: {
    voice: {
      name: 'ar-QA-MoazNeural',
    },
  },
  ['ar-sa-hamedneural']: {
    voice: {
      name: 'ar-SA-HamedNeural',
    },
  },
  ['ar-sa-zariyahneural']: {
    voice: {
      name: 'ar-SA-ZariyahNeural',
    },
  },
  ['ar-sy-amanyneural']: {
    voice: {
      name: 'ar-SY-AmanyNeural',
    },
  },
  ['ar-sy-laithneural']: {
    voice: {
      name: 'ar-SY-LaithNeural',
    },
  },
  ['ar-tn-hedineural']: {
    voice: {
      name: 'ar-TN-HediNeural',
    },
  },
  ['ar-tn-reemneural']: {
    voice: {
      name: 'ar-TN-ReemNeural',
    },
  },
  ['ar-ye-maryamneural']: {
    voice: {
      name: 'ar-YE-MaryamNeural',
    },
  },
  ['ar-ye-salehneural']: {
    voice: {
      name: 'ar-YE-SalehNeural',
    },
  },
  ['as-in-priyomneural']: {
    voice: {
      name: 'as-IN-PriyomNeural',
    },
  },
  ['as-in-yashicaneural']: {
    voice: {
      name: 'as-IN-YashicaNeural',
    },
  },
  ['az-az-babekneural']: {
    voice: {
      name: 'az-AZ-BabekNeural',
    },
  },
  ['az-az-banuneural']: {
    voice: {
      name: 'az-AZ-BanuNeural',
    },
  },
  ['bg-bg-borislavneural']: {
    voice: {
      name: 'bg-BG-BorislavNeural',
    },
  },
  ['bg-bg-kalinaneural']: {
    voice: {
      name: 'bg-BG-KalinaNeural',
    },
  },
  ['bn-bd-nabanitaneural']: {
    voice: {
      name: 'bn-BD-NabanitaNeural',
    },
  },
  ['bn-bd-pradeepneural']: {
    voice: {
      name: 'bn-BD-PradeepNeural',
    },
  },
  ['bn-in-bashkarneural']: {
    voice: {
      name: 'bn-IN-BashkarNeural',
    },
  },
  ['bn-in-tanishaaneural']: {
    voice: {
      name: 'bn-IN-TanishaaNeural',
    },
  },
  ['bs-ba-goranneural']: {
    voice: {
      name: 'bs-BA-GoranNeural',
    },
  },
  ['bs-ba-vesnaneural']: {
    voice: {
      name: 'bs-BA-VesnaNeural',
    },
  },
  ['ca-es-albaneural']: {
    voice: {
      name: 'ca-ES-AlbaNeural',
    },
  },
  ['ca-es-enricneural']: {
    voice: {
      name: 'ca-ES-EnricNeural',
    },
  },
  ['ca-es-joananeural']: {
    voice: {
      name: 'ca-ES-JoanaNeural',
    },
  },
  ['cs-cz-antoninneural']: {
    voice: {
      name: 'cs-CZ-AntoninNeural',
    },
  },
  ['cs-cz-vlastaneural']: {
    voice: {
      name: 'cs-CZ-VlastaNeural',
    },
  },
  ['cy-gb-aledneural']: {
    voice: {
      name: 'cy-GB-AledNeural',
    },
  },
  ['cy-gb-nianeural']: {
    voice: {
      name: 'cy-GB-NiaNeural',
    },
  },
  ['da-dk-christelneural']: {
    voice: {
      name: 'da-DK-ChristelNeural',
    },
  },
  ['da-dk-jeppeneural']: {
    voice: {
      name: 'da-DK-JeppeNeural',
    },
  },
  ['de-at-ingridneural']: {
    voice: {
      name: 'de-AT-IngridNeural',
    },
  },
  ['de-at-jonasneural']: {
    voice: {
      name: 'de-AT-JonasNeural',
    },
  },
  ['de-ch-janneural']: {
    voice: {
      name: 'de-CH-JanNeural',
    },
  },
  ['de-ch-lenineural']: {
    voice: {
      name: 'de-CH-LeniNeural',
    },
  },
  ['de-de-amalaneural']: {
    voice: {
      name: 'de-DE-AmalaNeural',
    },
  },
  ['de-de-berndneural']: {
    voice: {
      name: 'de-DE-BerndNeural',
    },
  },
  ['de-de-christophneural']: {
    voice: {
      name: 'de-DE-ChristophNeural',
    },
  },
  ['de-de-conradneural']: {
    voice: {
      name: 'de-DE-ConradNeural',
    },
  },
  ['de-de-elkeneural']: {
    voice: {
      name: 'de-DE-ElkeNeural',
    },
  },
  ['de-de-florianmultilingualneural']: {
    voice: {
      name: 'de-DE-FlorianMultilingualNeural',
    },
  },
  ['de-de-giselaneural']: {
    voice: {
      name: 'de-DE-GiselaNeural',
    },
  },
  ['de-de-kasperneural']: {
    voice: {
      name: 'de-DE-KasperNeural',
    },
  },
  ['de-de-katjaneural']: {
    voice: {
      name: 'de-DE-KatjaNeural',
    },
  },
  ['de-de-killianneural']: {
    voice: {
      name: 'de-DE-KillianNeural',
    },
  },
  ['de-de-klarissaneural']: {
    voice: {
      name: 'de-DE-KlarissaNeural',
    },
  },
  ['de-de-klausneural']: {
    voice: {
      name: 'de-DE-KlausNeural',
    },
  },
  ['de-de-louisaneural']: {
    voice: {
      name: 'de-DE-LouisaNeural',
    },
  },
  ['de-de-majaneural']: {
    voice: {
      name: 'de-DE-MajaNeural',
    },
  },
  ['de-de-ralfneural']: {
    voice: {
      name: 'de-DE-RalfNeural',
    },
  },
  ['de-de-seraphinamultilingualneural']: {
    voice: {
      name: 'de-DE-SeraphinaMultilingualNeural',
    },
  },
  ['de-de-tanjaneural']: {
    voice: {
      name: 'de-DE-TanjaNeural',
    },
  },
  ['el-gr-athinaneural']: {
    voice: {
      name: 'el-GR-AthinaNeural',
    },
  },
  ['el-gr-nestorasneural']: {
    voice: {
      name: 'el-GR-NestorasNeural',
    },
  },
  ['en-au-annetteneural']: {
    voice: {
      name: 'en-AU-AnnetteNeural',
    },
  },
  ['en-au-carlyneural']: {
    voice: {
      name: 'en-AU-CarlyNeural',
    },
  },
  ['en-au-darrenneural']: {
    voice: {
      name: 'en-AU-DarrenNeural',
    },
  },
  ['en-au-duncanneural']: {
    voice: {
      name: 'en-AU-DuncanNeural',
    },
  },
  ['en-au-elsieneural']: {
    voice: {
      name: 'en-AU-ElsieNeural',
    },
  },
  ['en-au-freyaneural']: {
    voice: {
      name: 'en-AU-FreyaNeural',
    },
  },
  ['en-au-joanneneural']: {
    voice: {
      name: 'en-AU-JoanneNeural',
    },
  },
  ['en-au-kenneural']: {
    voice: {
      name: 'en-AU-KenNeural',
    },
  },
  ['en-au-kimneural']: {
    voice: {
      name: 'en-AU-KimNeural',
    },
  },
  ['en-au-natashaneural']: {
    voice: {
      name: 'en-AU-NatashaNeural',
    },
  },
  ['en-au-neilneural']: {
    voice: {
      name: 'en-AU-NeilNeural',
    },
  },
  ['en-au-timneural']: {
    voice: {
      name: 'en-AU-TimNeural',
    },
  },
  ['en-au-tinaneural']: {
    voice: {
      name: 'en-AU-TinaNeural',
    },
  },
  ['en-au-williammultilingualneural']: {
    voice: {
      name: 'en-AU-WilliamMultilingualNeural',
    },
  },
  ['en-au-williamneural']: {
    voice: {
      name: 'en-AU-WilliamNeural',
    },
  },
  ['en-ca-claraneural']: {
    voice: {
      name: 'en-CA-ClaraNeural',
    },
  },
  ['en-ca-liamneural']: {
    voice: {
      name: 'en-CA-LiamNeural',
    },
  },
  ['en-gb-abbineural']: {
    voice: {
      name: 'en-GB-AbbiNeural',
    },
  },
  ['en-gb-adamultilingualneural']: {
    voice: {
      name: 'en-GB-AdaMultilingualNeural',
    },
  },
  ['en-gb-alfieneural']: {
    voice: {
      name: 'en-GB-AlfieNeural',
    },
  },
  ['en-gb-bellaneural']: {
    voice: {
      name: 'en-GB-BellaNeural',
    },
  },
  ['en-gb-elliotneural']: {
    voice: {
      name: 'en-GB-ElliotNeural',
    },
  },
  ['en-gb-ethanneural']: {
    voice: {
      name: 'en-GB-EthanNeural',
    },
  },
  ['en-gb-hollieneural']: {
    voice: {
      name: 'en-GB-HollieNeural',
    },
  },
  ['en-gb-libbyneural']: {
    voice: {
      name: 'en-GB-LibbyNeural',
    },
  },
  ['en-gb-maisieneural']: {
    voice: {
      name: 'en-GB-MaisieNeural',
    },
  },
  ['en-gb-mianeural']: {
    voice: {
      name: 'en-GB-MiaNeural',
    },
  },
  ['en-gb-noahneural']: {
    voice: {
      name: 'en-GB-NoahNeural',
    },
  },
  ['en-gb-oliverneural']: {
    voice: {
      name: 'en-GB-OliverNeural',
    },
  },
  ['en-gb-olivianeural']: {
    voice: {
      name: 'en-GB-OliviaNeural',
    },
  },
  ['en-gb-olliemultilingualneural']: {
    voice: {
      name: 'en-GB-OllieMultilingualNeural',
    },
  },
  ['en-gb-ryanneural']: {
    voice: {
      name: 'en-GB-RyanNeural',
    },
  },
  ['en-gb-sonianeural']: {
    voice: {
      name: 'en-GB-SoniaNeural',
    },
  },
  ['en-gb-thomasneural']: {
    voice: {
      name: 'en-GB-ThomasNeural',
    },
  },
  ['en-hk-samneural']: {
    voice: {
      name: 'en-HK-SamNeural',
    },
  },
  ['en-hk-yanneural']: {
    voice: {
      name: 'en-HK-YanNeural',
    },
  },
  ['en-ie-connorneural']: {
    voice: {
      name: 'en-IE-ConnorNeural',
    },
  },
  ['en-ie-emilyneural']: {
    voice: {
      name: 'en-IE-EmilyNeural',
    },
  },
  ['en-in-aaravneural']: {
    voice: {
      name: 'en-IN-AaravNeural',
    },
  },
  ['en-in-aartiindicneural']: {
    voice: {
      name: 'en-IN-AartiIndicNeural',
    },
  },
  ['en-in-aartineural']: {
    voice: {
      name: 'en-IN-AartiNeural',
    },
  },
  ['en-in-aashineural']: {
    voice: {
      name: 'en-IN-AashiNeural',
    },
  },
  ['en-in-ananyaneural']: {
    voice: {
      name: 'en-IN-AnanyaNeural',
    },
  },
  ['en-in-arjunindicneural']: {
    voice: {
      name: 'en-IN-ArjunIndicNeural',
    },
  },
  ['en-in-arjunneural']: {
    voice: {
      name: 'en-IN-ArjunNeural',
    },
  },
  ['en-in-kavyaneural']: {
    voice: {
      name: 'en-IN-KavyaNeural',
    },
  },
  ['en-in-kunalneural']: {
    voice: {
      name: 'en-IN-KunalNeural',
    },
  },
  ['en-in-neerjaindicneural']: {
    voice: {
      name: 'en-IN-NeerjaIndicNeural',
    },
  },
  ['en-in-neerjaneural']: {
    voice: {
      name: 'en-IN-NeerjaNeural',
    },
  },
  ['en-in-prabhatindicneural']: {
    voice: {
      name: 'en-IN-PrabhatIndicNeural',
    },
  },
  ['en-in-prabhatneural']: {
    voice: {
      name: 'en-IN-PrabhatNeural',
    },
  },
  ['en-in-rehaanneural']: {
    voice: {
      name: 'en-IN-RehaanNeural',
    },
  },
  ['en-ke-asilianeural']: {
    voice: {
      name: 'en-KE-AsiliaNeural',
    },
  },
  ['en-ke-chilembaneural']: {
    voice: {
      name: 'en-KE-ChilembaNeural',
    },
  },
  ['en-ng-abeoneural']: {
    voice: {
      name: 'en-NG-AbeoNeural',
    },
  },
  ['en-ng-ezinneneural']: {
    voice: {
      name: 'en-NG-EzinneNeural',
    },
  },
  ['en-nz-mitchellneural']: {
    voice: {
      name: 'en-NZ-MitchellNeural',
    },
  },
  ['en-nz-mollyneural']: {
    voice: {
      name: 'en-NZ-MollyNeural',
    },
  },
  ['en-ph-jamesneural']: {
    voice: {
      name: 'en-PH-JamesNeural',
    },
  },
  ['en-ph-rosaneural']: {
    voice: {
      name: 'en-PH-RosaNeural',
    },
  },
  ['en-sg-lunaneural']: {
    voice: {
      name: 'en-SG-LunaNeural',
    },
  },
  ['en-sg-wayneneural']: {
    voice: {
      name: 'en-SG-WayneNeural',
    },
  },
  ['en-tz-elimuneural']: {
    voice: {
      name: 'en-TZ-ElimuNeural',
    },
  },
  ['en-tz-imanineural']: {
    voice: {
      name: 'en-TZ-ImaniNeural',
    },
  },
  ['en-us-adammultilingualneural']: {
    voice: {
      name: 'en-US-AdamMultilingualNeural',
    },
  },
  ['en-us-alloyturbomultilingualneural']: {
    voice: {
      name: 'en-US-AlloyTurboMultilingualNeural',
    },
  },
  ['en-us-amandamultilingualneural']: {
    voice: {
      name: 'en-US-AmandaMultilingualNeural',
    },
  },
  ['en-us-amberneural']: {
    voice: {
      name: 'en-US-AmberNeural',
    },
  },
  ['en-us-ananeural']: {
    voice: {
      name: 'en-US-AnaNeural',
    },
  },
  ['en-us-andrewmultilingualneural']: {
    voice: {
      name: 'en-US-AndrewMultilingualNeural',
    },
  },
  ['en-us-andrewneural']: {
    voice: {
      name: 'en-US-AndrewNeural',
    },
  },
  ['en-us-arianeural']: {
    voice: {
      name: 'en-US-AriaNeural',
    },
  },
  ['en-us-ashleyneural']: {
    voice: {
      name: 'en-US-AshleyNeural',
    },
  },
  ['en-us-avamultilingualneural']: {
    voice: {
      name: 'en-US-AvaMultilingualNeural',
    },
  },
  ['en-us-avaneural']: {
    voice: {
      name: 'en-US-AvaNeural',
    },
  },
  ['en-us-brandonmultilingualneural']: {
    voice: {
      name: 'en-US-BrandonMultilingualNeural',
    },
  },
  ['en-us-brandonneural']: {
    voice: {
      name: 'en-US-BrandonNeural',
    },
  },
  ['en-us-brianmultilingualneural']: {
    voice: {
      name: 'en-US-BrianMultilingualNeural',
    },
  },
  ['en-us-brianneural']: {
    voice: {
      name: 'en-US-BrianNeural',
    },
  },
  ['en-us-christophermultilingualneural']: {
    voice: {
      name: 'en-US-ChristopherMultilingualNeural',
    },
  },
  ['en-us-christopherneural']: {
    voice: {
      name: 'en-US-ChristopherNeural',
    },
  },
  ['en-us-coramultilingualneural']: {
    voice: {
      name: 'en-US-CoraMultilingualNeural',
    },
  },
  ['en-us-coraneural']: {
    voice: {
      name: 'en-US-CoraNeural',
    },
  },
  ['en-us-davismultilingualneural']: {
    voice: {
      name: 'en-US-DavisMultilingualNeural',
    },
  },
  ['en-us-davisneural']: {
    voice: {
      name: 'en-US-DavisNeural',
    },
  },
  ['en-us-derekmultilingualneural']: {
    voice: {
      name: 'en-US-DerekMultilingualNeural',
    },
  },
  ['en-us-dustinmultilingualneural']: {
    voice: {
      name: 'en-US-DustinMultilingualNeural',
    },
  },
  ['en-us-echoturbomultilingualneural']: {
    voice: {
      name: 'en-US-EchoTurboMultilingualNeural',
    },
  },
  ['en-us-elizabethneural']: {
    voice: {
      name: 'en-US-ElizabethNeural',
    },
  },
  ['en-us-emmamultilingualneural']: {
    voice: {
      name: 'en-US-EmmaMultilingualNeural',
    },
  },
  ['en-us-emmaneural']: {
    voice: {
      name: 'en-US-EmmaNeural',
    },
  },
  ['en-us-ericneural']: {
    voice: {
      name: 'en-US-EricNeural',
    },
  },
  ['en-us-fableturbomultilingualneural']: {
    voice: {
      name: 'en-US-FableTurboMultilingualNeural',
    },
  },
  ['en-us-guyneural']: {
    voice: {
      name: 'en-US-GuyNeural',
    },
  },
  ['en-us-jacobneural']: {
    voice: {
      name: 'en-US-JacobNeural',
    },
  },
  ['en-us-janeneural']: {
    voice: {
      name: 'en-US-JaneNeural',
    },
  },
  ['en-us-jasonneural']: {
    voice: {
      name: 'en-US-JasonNeural',
    },
  },
  ['en-us-jennymultilingualneural']: {
    voice: {
      name: 'en-US-JennyMultilingualNeural',
    },
  },
  ['en-us-jennyneural']: {
    voice: {
      name: 'en-US-JennyNeural',
    },
  },
  ['en-us-kaineural']: {
    voice: {
      name: 'en-US-KaiNeural',
    },
  },
  ['en-us-lewismultilingualneural']: {
    voice: {
      name: 'en-US-LewisMultilingualNeural',
    },
  },
  ['en-us-lolamultilingualneural']: {
    voice: {
      name: 'en-US-LolaMultilingualNeural',
    },
  },
  ['en-us-lunaneural']: {
    voice: {
      name: 'en-US-LunaNeural',
    },
  },
  ['en-us-michelleneural']: {
    voice: {
      name: 'en-US-MichelleNeural',
    },
  },
  ['en-us-monicaneural']: {
    voice: {
      name: 'en-US-MonicaNeural',
    },
  },
  ['en-us-nancymultilingualneural']: {
    voice: {
      name: 'en-US-NancyMultilingualNeural',
    },
  },
  ['en-us-nancyneural']: {
    voice: {
      name: 'en-US-NancyNeural',
    },
  },
  ['en-us-novaturbomultilingualneural']: {
    voice: {
      name: 'en-US-NovaTurboMultilingualNeural',
    },
  },
  ['en-us-onyxturbomultilingualneural']: {
    voice: {
      name: 'en-US-OnyxTurboMultilingualNeural',
    },
  },
  ['en-us-phoebemultilingualneural']: {
    voice: {
      name: 'en-US-PhoebeMultilingualNeural',
    },
  },
  ['en-us-rogerneural']: {
    voice: {
      name: 'en-US-RogerNeural',
    },
  },
  ['en-us-ryanmultilingualneural']: {
    voice: {
      name: 'en-US-RyanMultilingualNeural',
    },
  },
  ['en-us-samuelmultilingualneural']: {
    voice: {
      name: 'en-US-SamuelMultilingualNeural',
    },
  },
  ['en-us-saraneural']: {
    voice: {
      name: 'en-US-SaraNeural',
    },
  },
  ['en-us-serenamultilingualneural']: {
    voice: {
      name: 'en-US-SerenaMultilingualNeural',
    },
  },
  ['en-us-shimmerturbomultilingualneural']: {
    voice: {
      name: 'en-US-ShimmerTurboMultilingualNeural',
    },
  },
  ['en-us-steffanmultilingualneural']: {
    voice: {
      name: 'en-US-SteffanMultilingualNeural',
    },
  },
  ['en-us-steffanneural']: {
    voice: {
      name: 'en-US-SteffanNeural',
    },
  },
  ['en-us-tonyneural']: {
    voice: {
      name: 'en-US-TonyNeural',
    },
  },
  ['en-za-leahneural']: {
    voice: {
      name: 'en-ZA-LeahNeural',
    },
  },
  ['en-za-lukeneural']: {
    voice: {
      name: 'en-ZA-LukeNeural',
    },
  },
  ['es-ar-elenaneural']: {
    voice: {
      name: 'es-AR-ElenaNeural',
    },
  },
  ['es-ar-tomasneural']: {
    voice: {
      name: 'es-AR-TomasNeural',
    },
  },
  ['es-bo-marceloneural']: {
    voice: {
      name: 'es-BO-MarceloNeural',
    },
  },
  ['es-bo-sofianeural']: {
    voice: {
      name: 'es-BO-SofiaNeural',
    },
  },
  ['es-cl-catalinaneural']: {
    voice: {
      name: 'es-CL-CatalinaNeural',
    },
  },
  ['es-cl-lorenzoneural']: {
    voice: {
      name: 'es-CL-LorenzoNeural',
    },
  },
  ['es-co-gonzaloneural']: {
    voice: {
      name: 'es-CO-GonzaloNeural',
    },
  },
  ['es-co-salomeneural']: {
    voice: {
      name: 'es-CO-SalomeNeural',
    },
  },
  ['es-cr-juanneural']: {
    voice: {
      name: 'es-CR-JuanNeural',
    },
  },
  ['es-cr-marianeural']: {
    voice: {
      name: 'es-CR-MariaNeural',
    },
  },
  ['es-cu-belkysneural']: {
    voice: {
      name: 'es-CU-BelkysNeural',
    },
  },
  ['es-cu-manuelneural']: {
    voice: {
      name: 'es-CU-ManuelNeural',
    },
  },
  ['es-do-emilioneural']: {
    voice: {
      name: 'es-DO-EmilioNeural',
    },
  },
  ['es-do-ramonaneural']: {
    voice: {
      name: 'es-DO-RamonaNeural',
    },
  },
  ['es-ec-andreaneural']: {
    voice: {
      name: 'es-EC-AndreaNeural',
    },
  },
  ['es-ec-luisneural']: {
    voice: {
      name: 'es-EC-LuisNeural',
    },
  },
  ['es-es-abrilneural']: {
    voice: {
      name: 'es-ES-AbrilNeural',
    },
  },
  ['es-es-alvaroneural']: {
    voice: {
      name: 'es-ES-AlvaroNeural',
    },
  },
  ['es-es-arabellamultilingualneural']: {
    voice: {
      name: 'es-ES-ArabellaMultilingualNeural',
    },
  },
  ['es-es-arnauneural']: {
    voice: {
      name: 'es-ES-ArnauNeural',
    },
  },
  ['es-es-darioneural']: {
    voice: {
      name: 'es-ES-DarioNeural',
    },
  },
  ['es-es-eliasneural']: {
    voice: {
      name: 'es-ES-EliasNeural',
    },
  },
  ['es-es-elviraneural']: {
    voice: {
      name: 'es-ES-ElviraNeural',
    },
  },
  ['es-es-estrellaneural']: {
    voice: {
      name: 'es-ES-EstrellaNeural',
    },
  },
  ['es-es-ireneneural']: {
    voice: {
      name: 'es-ES-IreneNeural',
    },
  },
  ['es-es-isidoramultilingualneural']: {
    voice: {
      name: 'es-ES-IsidoraMultilingualNeural',
    },
  },
  ['es-es-laianeural']: {
    voice: {
      name: 'es-ES-LaiaNeural',
    },
  },
  ['es-es-lianeural']: {
    voice: {
      name: 'es-ES-LiaNeural',
    },
  },
  ['es-es-nilneural']: {
    voice: {
      name: 'es-ES-NilNeural',
    },
  },
  ['es-es-saulneural']: {
    voice: {
      name: 'es-ES-SaulNeural',
    },
  },
  ['es-es-teoneural']: {
    voice: {
      name: 'es-ES-TeoNeural',
    },
  },
  ['es-es-triananeural']: {
    voice: {
      name: 'es-ES-TrianaNeural',
    },
  },
  ['es-es-tristanmultilingualneural']: {
    voice: {
      name: 'es-ES-TristanMultilingualNeural',
    },
  },
  ['es-es-veraneural']: {
    voice: {
      name: 'es-ES-VeraNeural',
    },
  },
  ['es-es-ximenamultilingualneural']: {
    voice: {
      name: 'es-ES-XimenaMultilingualNeural',
    },
  },
  ['es-es-ximenaneural']: {
    voice: {
      name: 'es-ES-XimenaNeural',
    },
  },
  ['es-gq-javierneural']: {
    voice: {
      name: 'es-GQ-JavierNeural',
    },
  },
  ['es-gq-teresaneural']: {
    voice: {
      name: 'es-GQ-TeresaNeural',
    },
  },
  ['es-gt-andresneural']: {
    voice: {
      name: 'es-GT-AndresNeural',
    },
  },
  ['es-gt-martaneural']: {
    voice: {
      name: 'es-GT-MartaNeural',
    },
  },
  ['es-hn-carlosneural']: {
    voice: {
      name: 'es-HN-CarlosNeural',
    },
  },
  ['es-hn-karlaneural']: {
    voice: {
      name: 'es-HN-KarlaNeural',
    },
  },
  ['es-mx-beatrizneural']: {
    voice: {
      name: 'es-MX-BeatrizNeural',
    },
  },
  ['es-mx-candelaneural']: {
    voice: {
      name: 'es-MX-CandelaNeural',
    },
  },
  ['es-mx-carlotaneural']: {
    voice: {
      name: 'es-MX-CarlotaNeural',
    },
  },
  ['es-mx-cecilioneural']: {
    voice: {
      name: 'es-MX-CecilioNeural',
    },
  },
  ['es-mx-daliamultilingualneural']: {
    voice: {
      name: 'es-MX-DaliaMultilingualNeural',
    },
  },
  ['es-mx-dalianeural']: {
    voice: {
      name: 'es-MX-DaliaNeural',
    },
  },
  ['es-mx-gerardoneural']: {
    voice: {
      name: 'es-MX-GerardoNeural',
    },
  },
  ['es-mx-jorgemultilingualneural']: {
    voice: {
      name: 'es-MX-JorgeMultilingualNeural',
    },
  },
  ['es-mx-jorgeneural']: {
    voice: {
      name: 'es-MX-JorgeNeural',
    },
  },
  ['es-mx-larissaneural']: {
    voice: {
      name: 'es-MX-LarissaNeural',
    },
  },
  ['es-mx-libertoneural']: {
    voice: {
      name: 'es-MX-LibertoNeural',
    },
  },
  ['es-mx-lucianoneural']: {
    voice: {
      name: 'es-MX-LucianoNeural',
    },
  },
  ['es-mx-marinaneural']: {
    voice: {
      name: 'es-MX-MarinaNeural',
    },
  },
  ['es-mx-nurianeural']: {
    voice: {
      name: 'es-MX-NuriaNeural',
    },
  },
  ['es-mx-pelayoneural']: {
    voice: {
      name: 'es-MX-PelayoNeural',
    },
  },
  ['es-mx-renataneural']: {
    voice: {
      name: 'es-MX-RenataNeural',
    },
  },
  ['es-mx-yagoneural']: {
    voice: {
      name: 'es-MX-YagoNeural',
    },
  },
  ['es-ni-federiconeural']: {
    voice: {
      name: 'es-NI-FedericoNeural',
    },
  },
  ['es-ni-yolandaneural']: {
    voice: {
      name: 'es-NI-YolandaNeural',
    },
  },
  ['es-pa-margaritaneural']: {
    voice: {
      name: 'es-PA-MargaritaNeural',
    },
  },
  ['es-pa-robertoneural']: {
    voice: {
      name: 'es-PA-RobertoNeural',
    },
  },
  ['es-pe-alexneural']: {
    voice: {
      name: 'es-PE-AlexNeural',
    },
  },
  ['es-pe-camilaneural']: {
    voice: {
      name: 'es-PE-CamilaNeural',
    },
  },
  ['es-pr-karinaneural']: {
    voice: {
      name: 'es-PR-KarinaNeural',
    },
  },
  ['es-pr-victorneural']: {
    voice: {
      name: 'es-PR-VictorNeural',
    },
  },
  ['es-py-marioneural']: {
    voice: {
      name: 'es-PY-MarioNeural',
    },
  },
  ['es-py-tanianeural']: {
    voice: {
      name: 'es-PY-TaniaNeural',
    },
  },
  ['es-sv-lorenaneural']: {
    voice: {
      name: 'es-SV-LorenaNeural',
    },
  },
  ['es-sv-rodrigoneural']: {
    voice: {
      name: 'es-SV-RodrigoNeural',
    },
  },
  ['es-us-alonsoneural']: {
    voice: {
      name: 'es-US-AlonsoNeural',
    },
  },
  ['es-us-palomaneural']: {
    voice: {
      name: 'es-US-PalomaNeural',
    },
  },
  ['es-uy-mateoneural']: {
    voice: {
      name: 'es-UY-MateoNeural',
    },
  },
  ['es-uy-valentinaneural']: {
    voice: {
      name: 'es-UY-ValentinaNeural',
    },
  },
  ['es-ve-paolaneural']: {
    voice: {
      name: 'es-VE-PaolaNeural',
    },
  },
  ['es-ve-sebastianneural']: {
    voice: {
      name: 'es-VE-SebastianNeural',
    },
  },
  ['et-ee-anuneural']: {
    voice: {
      name: 'et-EE-AnuNeural',
    },
  },
  ['et-ee-kertneural']: {
    voice: {
      name: 'et-EE-KertNeural',
    },
  },
  ['eu-es-ainhoaneural']: {
    voice: {
      name: 'eu-ES-AinhoaNeural',
    },
  },
  ['eu-es-anderneural']: {
    voice: {
      name: 'eu-ES-AnderNeural',
    },
  },
  ['fa-ir-dilaraneural']: {
    voice: {
      name: 'fa-IR-DilaraNeural',
    },
  },
  ['fa-ir-faridneural']: {
    voice: {
      name: 'fa-IR-FaridNeural',
    },
  },
  ['fi-fi-harrineural']: {
    voice: {
      name: 'fi-FI-HarriNeural',
    },
  },
  ['fi-fi-nooraneural']: {
    voice: {
      name: 'fi-FI-NooraNeural',
    },
  },
  ['fi-fi-selmaneural']: {
    voice: {
      name: 'fi-FI-SelmaNeural',
    },
  },
  ['fil-ph-angeloneural']: {
    voice: {
      name: 'fil-PH-AngeloNeural',
    },
  },
  ['fil-ph-blessicaneural']: {
    voice: {
      name: 'fil-PH-BlessicaNeural',
    },
  },
  ['fr-be-charlineneural']: {
    voice: {
      name: 'fr-BE-CharlineNeural',
    },
  },
  ['fr-be-gerardneural']: {
    voice: {
      name: 'fr-BE-GerardNeural',
    },
  },
  ['fr-ca-antoineneural']: {
    voice: {
      name: 'fr-CA-AntoineNeural',
    },
  },
  ['fr-ca-jeanneural']: {
    voice: {
      name: 'fr-CA-JeanNeural',
    },
  },
  ['fr-ca-sylvieneural']: {
    voice: {
      name: 'fr-CA-SylvieNeural',
    },
  },
  ['fr-ca-thierryneural']: {
    voice: {
      name: 'fr-CA-ThierryNeural',
    },
  },
  ['fr-ch-arianeneural']: {
    voice: {
      name: 'fr-CH-ArianeNeural',
    },
  },
  ['fr-ch-fabriceneural']: {
    voice: {
      name: 'fr-CH-FabriceNeural',
    },
  },
  ['fr-fr-alainneural']: {
    voice: {
      name: 'fr-FR-AlainNeural',
    },
  },
  ['fr-fr-brigitteneural']: {
    voice: {
      name: 'fr-FR-BrigitteNeural',
    },
  },
  ['fr-fr-celesteneural']: {
    voice: {
      name: 'fr-FR-CelesteNeural',
    },
  },
  ['fr-fr-claudeneural']: {
    voice: {
      name: 'fr-FR-ClaudeNeural',
    },
  },
  ['fr-fr-coralieneural']: {
    voice: {
      name: 'fr-FR-CoralieNeural',
    },
  },
  ['fr-fr-deniseneural']: {
    voice: {
      name: 'fr-FR-DeniseNeural',
    },
  },
  ['fr-fr-eloiseneural']: {
    voice: {
      name: 'fr-FR-EloiseNeural',
    },
  },
  ['fr-fr-henrineural']: {
    voice: {
      name: 'fr-FR-HenriNeural',
    },
  },
  ['fr-fr-jacquelineneural']: {
    voice: {
      name: 'fr-FR-JacquelineNeural',
    },
  },
  ['fr-fr-jeromeneural']: {
    voice: {
      name: 'fr-FR-JeromeNeural',
    },
  },
  ['fr-fr-josephineneural']: {
    voice: {
      name: 'fr-FR-JosephineNeural',
    },
  },
  ['fr-fr-lucienmultilingualneural']: {
    voice: {
      name: 'fr-FR-LucienMultilingualNeural',
    },
  },
  ['fr-fr-mauriceneural']: {
    voice: {
      name: 'fr-FR-MauriceNeural',
    },
  },
  ['fr-fr-remymultilingualneural']: {
    voice: {
      name: 'fr-FR-RemyMultilingualNeural',
    },
  },
  ['fr-fr-viviennemultilingualneural']: {
    voice: {
      name: 'fr-FR-VivienneMultilingualNeural',
    },
  },
  ['fr-fr-yvesneural']: {
    voice: {
      name: 'fr-FR-YvesNeural',
    },
  },
  ['fr-fr-yvetteneural']: {
    voice: {
      name: 'fr-FR-YvetteNeural',
    },
  },
  ['ga-ie-colmneural']: {
    voice: {
      name: 'ga-IE-ColmNeural',
    },
  },
  ['ga-ie-orlaneural']: {
    voice: {
      name: 'ga-IE-OrlaNeural',
    },
  },
  ['gl-es-roineural']: {
    voice: {
      name: 'gl-ES-RoiNeural',
    },
  },
  ['gl-es-sabelaneural']: {
    voice: {
      name: 'gl-ES-SabelaNeural',
    },
  },
  ['gu-in-dhwanineural']: {
    voice: {
      name: 'gu-IN-DhwaniNeural',
    },
  },
  ['gu-in-niranjanneural']: {
    voice: {
      name: 'gu-IN-NiranjanNeural',
    },
  },
  ['he-il-avrineural']: {
    voice: {
      name: 'he-IL-AvriNeural',
    },
  },
  ['he-il-hilaneural']: {
    voice: {
      name: 'he-IL-HilaNeural',
    },
  },
  ['hi-in-aaravneural']: {
    voice: {
      name: 'hi-IN-AaravNeural',
    },
  },
  ['hi-in-aartineural']: {
    voice: {
      name: 'hi-IN-AartiNeural',
    },
  },
  ['hi-in-ananyaneural']: {
    voice: {
      name: 'hi-IN-AnanyaNeural',
    },
  },
  ['hi-in-arjunneural']: {
    voice: {
      name: 'hi-IN-ArjunNeural',
    },
  },
  ['hi-in-kavyaneural']: {
    voice: {
      name: 'hi-IN-KavyaNeural',
    },
  },
  ['hi-in-kunalneural']: {
    voice: {
      name: 'hi-IN-KunalNeural',
    },
  },
  ['hi-in-madhurneural']: {
    voice: {
      name: 'hi-IN-MadhurNeural',
    },
  },
  ['hi-in-rehaanneural']: {
    voice: {
      name: 'hi-IN-RehaanNeural',
    },
  },
  ['hi-in-swaraneural']: {
    voice: {
      name: 'hi-IN-SwaraNeural',
    },
  },
  ['hr-hr-gabrijelaneural']: {
    voice: {
      name: 'hr-HR-GabrijelaNeural',
    },
  },
  ['hr-hr-sreckoneural']: {
    voice: {
      name: 'hr-HR-SreckoNeural',
    },
  },
  ['hu-hu-noemineural']: {
    voice: {
      name: 'hu-HU-NoemiNeural',
    },
  },
  ['hu-hu-tamasneural']: {
    voice: {
      name: 'hu-HU-TamasNeural',
    },
  },
  ['hy-am-anahitneural']: {
    voice: {
      name: 'hy-AM-AnahitNeural',
    },
  },
  ['hy-am-haykneural']: {
    voice: {
      name: 'hy-AM-HaykNeural',
    },
  },
  ['id-id-ardineural']: {
    voice: {
      name: 'id-ID-ArdiNeural',
    },
  },
  ['id-id-gadisneural']: {
    voice: {
      name: 'id-ID-GadisNeural',
    },
  },
  ['is-is-gudrunneural']: {
    voice: {
      name: 'is-IS-GudrunNeural',
    },
  },
  ['is-is-gunnarneural']: {
    voice: {
      name: 'is-IS-GunnarNeural',
    },
  },
  ['it-it-alessiomultilingualneural']: {
    voice: {
      name: 'it-IT-AlessioMultilingualNeural',
    },
  },
  ['it-it-benignoneural']: {
    voice: {
      name: 'it-IT-BenignoNeural',
    },
  },
  ['it-it-calimeroneural']: {
    voice: {
      name: 'it-IT-CalimeroNeural',
    },
  },
  ['it-it-cataldoneural']: {
    voice: {
      name: 'it-IT-CataldoNeural',
    },
  },
  ['it-it-diegoneural']: {
    voice: {
      name: 'it-IT-DiegoNeural',
    },
  },
  ['it-it-elsaneural']: {
    voice: {
      name: 'it-IT-ElsaNeural',
    },
  },
  ['it-it-fabiolaneural']: {
    voice: {
      name: 'it-IT-FabiolaNeural',
    },
  },
  ['it-it-fiammaneural']: {
    voice: {
      name: 'it-IT-FiammaNeural',
    },
  },
  ['it-it-giannineural']: {
    voice: {
      name: 'it-IT-GianniNeural',
    },
  },
  ['it-it-giuseppemultilingualneural']: {
    voice: {
      name: 'it-IT-GiuseppeMultilingualNeural',
    },
  },
  ['it-it-giuseppeneural']: {
    voice: {
      name: 'it-IT-GiuseppeNeural',
    },
  },
  ['it-it-imeldaneural']: {
    voice: {
      name: 'it-IT-ImeldaNeural',
    },
  },
  ['it-it-irmaneural']: {
    voice: {
      name: 'it-IT-IrmaNeural',
    },
  },
  ['it-it-isabellamultilingualneural']: {
    voice: {
      name: 'it-IT-IsabellaMultilingualNeural',
    },
  },
  ['it-it-isabellaneural']: {
    voice: {
      name: 'it-IT-IsabellaNeural',
    },
  },
  ['it-it-lisandroneural']: {
    voice: {
      name: 'it-IT-LisandroNeural',
    },
  },
  ['it-it-marcellomultilingualneural']: {
    voice: {
      name: 'it-IT-MarcelloMultilingualNeural',
    },
  },
  ['it-it-palmiraneural']: {
    voice: {
      name: 'it-IT-PalmiraNeural',
    },
  },
  ['it-it-pierinaneural']: {
    voice: {
      name: 'it-IT-PierinaNeural',
    },
  },
  ['it-it-rinaldoneural']: {
    voice: {
      name: 'it-IT-RinaldoNeural',
    },
  },
  ['iu-cans-ca-siqiniqneural']: {
    voice: {
      name: 'iu-Cans-CA-SiqiniqNeural',
    },
  },
  ['iu-cans-ca-taqqiqneural']: {
    voice: {
      name: 'iu-Cans-CA-TaqqiqNeural',
    },
  },
  ['iu-latn-ca-siqiniqneural']: {
    voice: {
      name: 'iu-Latn-CA-SiqiniqNeural',
    },
  },
  ['iu-latn-ca-taqqiqneural']: {
    voice: {
      name: 'iu-Latn-CA-TaqqiqNeural',
    },
  },
  ['ja-jp-aoineural']: {
    voice: {
      name: 'ja-JP-AoiNeural',
    },
  },
  ['ja-jp-daichineural']: {
    voice: {
      name: 'ja-JP-DaichiNeural',
    },
  },
  ['ja-jp-keitaneural']: {
    voice: {
      name: 'ja-JP-KeitaNeural',
    },
  },
  ['ja-jp-mayuneural']: {
    voice: {
      name: 'ja-JP-MayuNeural',
    },
  },
  ['ja-jp-nanamineural']: {
    voice: {
      name: 'ja-JP-NanamiNeural',
    },
  },
  ['ja-jp-naokineural']: {
    voice: {
      name: 'ja-JP-NaokiNeural',
    },
  },
  ['ja-jp-shiorineural']: {
    voice: {
      name: 'ja-JP-ShioriNeural',
    },
  },
  ['jv-id-dimasneural']: {
    voice: {
      name: 'jv-ID-DimasNeural',
    },
  },
  ['jv-id-sitineural']: {
    voice: {
      name: 'jv-ID-SitiNeural',
    },
  },
  ['ka-ge-ekaneural']: {
    voice: {
      name: 'ka-GE-EkaNeural',
    },
  },
  ['ka-ge-giorgineural']: {
    voice: {
      name: 'ka-GE-GiorgiNeural',
    },
  },
  ['kk-kz-aigulneural']: {
    voice: {
      name: 'kk-KZ-AigulNeural',
    },
  },
  ['kk-kz-dauletneural']: {
    voice: {
      name: 'kk-KZ-DauletNeural',
    },
  },
  ['km-kh-pisethneural']: {
    voice: {
      name: 'km-KH-PisethNeural',
    },
  },
  ['km-kh-sreymomneural']: {
    voice: {
      name: 'km-KH-SreymomNeural',
    },
  },
  ['kn-in-gaganneural']: {
    voice: {
      name: 'kn-IN-GaganNeural',
    },
  },
  ['kn-in-sapnaneural']: {
    voice: {
      name: 'kn-IN-SapnaNeural',
    },
  },
  ['ko-kr-bongjinneural']: {
    voice: {
      name: 'ko-KR-BongJinNeural',
    },
  },
  ['ko-kr-gookminneural']: {
    voice: {
      name: 'ko-KR-GookMinNeural',
    },
  },
  ['ko-kr-hyunsumultilingualneural']: {
    voice: {
      name: 'ko-KR-HyunsuMultilingualNeural',
    },
  },
  ['ko-kr-hyunsuneural']: {
    voice: {
      name: 'ko-KR-HyunsuNeural',
    },
  },
  ['ko-kr-injoonneural']: {
    voice: {
      name: 'ko-KR-InJoonNeural',
    },
  },
  ['ko-kr-jiminneural']: {
    voice: {
      name: 'ko-KR-JiMinNeural',
    },
  },
  ['ko-kr-seohyeonneural']: {
    voice: {
      name: 'ko-KR-SeoHyeonNeural',
    },
  },
  ['ko-kr-soonbokneural']: {
    voice: {
      name: 'ko-KR-SoonBokNeural',
    },
  },
  ['ko-kr-sunhineural']: {
    voice: {
      name: 'ko-KR-SunHiNeural',
    },
  },
  ['ko-kr-yujinneural']: {
    voice: {
      name: 'ko-KR-YuJinNeural',
    },
  },
  ['lo-la-chanthavongneural']: {
    voice: {
      name: 'lo-LA-ChanthavongNeural',
    },
  },
  ['lo-la-keomanyneural']: {
    voice: {
      name: 'lo-LA-KeomanyNeural',
    },
  },
  ['lt-lt-leonasneural']: {
    voice: {
      name: 'lt-LT-LeonasNeural',
    },
  },
  ['lt-lt-onaneural']: {
    voice: {
      name: 'lt-LT-OnaNeural',
    },
  },
  ['lv-lv-everitaneural']: {
    voice: {
      name: 'lv-LV-EveritaNeural',
    },
  },
  ['lv-lv-nilsneural']: {
    voice: {
      name: 'lv-LV-NilsNeural',
    },
  },
  ['mk-mk-aleksandarneural']: {
    voice: {
      name: 'mk-MK-AleksandarNeural',
    },
  },
  ['mk-mk-marijaneural']: {
    voice: {
      name: 'mk-MK-MarijaNeural',
    },
  },
  ['ml-in-midhunneural']: {
    voice: {
      name: 'ml-IN-MidhunNeural',
    },
  },
  ['ml-in-sobhananeural']: {
    voice: {
      name: 'ml-IN-SobhanaNeural',
    },
  },
  ['mn-mn-bataaneural']: {
    voice: {
      name: 'mn-MN-BataaNeural',
    },
  },
  ['mn-mn-yesuineural']: {
    voice: {
      name: 'mn-MN-YesuiNeural',
    },
  },
  ['mr-in-aarohineural']: {
    voice: {
      name: 'mr-IN-AarohiNeural',
    },
  },
  ['mr-in-manoharneural']: {
    voice: {
      name: 'mr-IN-ManoharNeural',
    },
  },
  ['ms-my-osmanneural']: {
    voice: {
      name: 'ms-MY-OsmanNeural',
    },
  },
  ['ms-my-yasminneural']: {
    voice: {
      name: 'ms-MY-YasminNeural',
    },
  },
  ['mt-mt-graceneural']: {
    voice: {
      name: 'mt-MT-GraceNeural',
    },
  },
  ['mt-mt-josephneural']: {
    voice: {
      name: 'mt-MT-JosephNeural',
    },
  },
  ['my-mm-nilarneural']: {
    voice: {
      name: 'my-MM-NilarNeural',
    },
  },
  ['my-mm-thihaneural']: {
    voice: {
      name: 'my-MM-ThihaNeural',
    },
  },
  ['nb-no-finnneural']: {
    voice: {
      name: 'nb-NO-FinnNeural',
    },
  },
  ['nb-no-iselinneural']: {
    voice: {
      name: 'nb-NO-IselinNeural',
    },
  },
  ['nb-no-pernilleneural']: {
    voice: {
      name: 'nb-NO-PernilleNeural',
    },
  },
  ['ne-np-hemkalaneural']: {
    voice: {
      name: 'ne-NP-HemkalaNeural',
    },
  },
  ['ne-np-sagarneural']: {
    voice: {
      name: 'ne-NP-SagarNeural',
    },
  },
  ['nl-be-arnaudneural']: {
    voice: {
      name: 'nl-BE-ArnaudNeural',
    },
  },
  ['nl-be-denaneural']: {
    voice: {
      name: 'nl-BE-DenaNeural',
    },
  },
  ['nl-nl-coletteneural']: {
    voice: {
      name: 'nl-NL-ColetteNeural',
    },
  },
  ['nl-nl-fennaneural']: {
    voice: {
      name: 'nl-NL-FennaNeural',
    },
  },
  ['nl-nl-maartenneural']: {
    voice: {
      name: 'nl-NL-MaartenNeural',
    },
  },
  ['or-in-subhasinineural']: {
    voice: {
      name: 'or-IN-SubhasiniNeural',
    },
  },
  ['or-in-sukantneural']: {
    voice: {
      name: 'or-IN-SukantNeural',
    },
  },
  ['pa-in-ojasneural']: {
    voice: {
      name: 'pa-IN-OjasNeural',
    },
  },
  ['pa-in-vaanineural']: {
    voice: {
      name: 'pa-IN-VaaniNeural',
    },
  },
  ['pl-pl-agnieszkaneural']: {
    voice: {
      name: 'pl-PL-AgnieszkaNeural',
    },
  },
  ['pl-pl-marekneural']: {
    voice: {
      name: 'pl-PL-MarekNeural',
    },
  },
  ['pl-pl-zofianeural']: {
    voice: {
      name: 'pl-PL-ZofiaNeural',
    },
  },
  ['ps-af-gulnawazneural']: {
    voice: {
      name: 'ps-AF-GulNawazNeural',
    },
  },
  ['ps-af-latifaneural']: {
    voice: {
      name: 'ps-AF-LatifaNeural',
    },
  },
  ['pt-br-antonioneural']: {
    voice: {
      name: 'pt-BR-AntonioNeural',
    },
  },
  ['pt-br-brendaneural']: {
    voice: {
      name: 'pt-BR-BrendaNeural',
    },
  },
  ['pt-br-donatoneural']: {
    voice: {
      name: 'pt-BR-DonatoNeural',
    },
  },
  ['pt-br-elzaneural']: {
    voice: {
      name: 'pt-BR-ElzaNeural',
    },
  },
  ['pt-br-fabioneural']: {
    voice: {
      name: 'pt-BR-FabioNeural',
    },
  },
  ['pt-br-franciscaneural']: {
    voice: {
      name: 'pt-BR-FranciscaNeural',
    },
  },
  ['pt-br-giovannaneural']: {
    voice: {
      name: 'pt-BR-GiovannaNeural',
    },
  },
  ['pt-br-humbertoneural']: {
    voice: {
      name: 'pt-BR-HumbertoNeural',
    },
  },
  ['pt-br-julioneural']: {
    voice: {
      name: 'pt-BR-JulioNeural',
    },
  },
  ['pt-br-leilaneural']: {
    voice: {
      name: 'pt-BR-LeilaNeural',
    },
  },
  ['pt-br-leticianeural']: {
    voice: {
      name: 'pt-BR-LeticiaNeural',
    },
  },
  ['pt-br-maceriomultilingualneural']: {
    voice: {
      name: 'pt-BR-MacerioMultilingualNeural',
    },
  },
  ['pt-br-manuelaneural']: {
    voice: {
      name: 'pt-BR-ManuelaNeural',
    },
  },
  ['pt-br-nicolauneural']: {
    voice: {
      name: 'pt-BR-NicolauNeural',
    },
  },
  ['pt-br-thalitamultilingualneural']: {
    voice: {
      name: 'pt-BR-ThalitaMultilingualNeural',
    },
  },
  ['pt-br-thalitaneural']: {
    voice: {
      name: 'pt-BR-ThalitaNeural',
    },
  },
  ['pt-br-valerioneural']: {
    voice: {
      name: 'pt-BR-ValerioNeural',
    },
  },
  ['pt-br-yaraneural']: {
    voice: {
      name: 'pt-BR-YaraNeural',
    },
  },
  ['pt-pt-duarteneural']: {
    voice: {
      name: 'pt-PT-DuarteNeural',
    },
  },
  ['pt-pt-fernandaneural']: {
    voice: {
      name: 'pt-PT-FernandaNeural',
    },
  },
  ['pt-pt-raquelneural']: {
    voice: {
      name: 'pt-PT-RaquelNeural',
    },
  },
  ['ro-ro-alinaneural']: {
    voice: {
      name: 'ro-RO-AlinaNeural',
    },
  },
  ['ro-ro-emilneural']: {
    voice: {
      name: 'ro-RO-EmilNeural',
    },
  },
  ['ru-ru-dariyaneural']: {
    voice: {
      name: 'ru-RU-DariyaNeural',
    },
  },
  ['ru-ru-dmitryneural']: {
    voice: {
      name: 'ru-RU-DmitryNeural',
    },
  },
  ['ru-ru-svetlananeural']: {
    voice: {
      name: 'ru-RU-SvetlanaNeural',
    },
  },
  ['si-lk-sameeraneural']: {
    voice: {
      name: 'si-LK-SameeraNeural',
    },
  },
  ['si-lk-thilinineural']: {
    voice: {
      name: 'si-LK-ThiliniNeural',
    },
  },
  ['sk-sk-lukasneural']: {
    voice: {
      name: 'sk-SK-LukasNeural',
    },
  },
  ['sk-sk-viktorianeural']: {
    voice: {
      name: 'sk-SK-ViktoriaNeural',
    },
  },
  ['sl-si-petraneural']: {
    voice: {
      name: 'sl-SI-PetraNeural',
    },
  },
  ['sl-si-rokneural']: {
    voice: {
      name: 'sl-SI-RokNeural',
    },
  },
  ['so-so-muuseneural']: {
    voice: {
      name: 'so-SO-MuuseNeural',
    },
  },
  ['so-so-ubaxneural']: {
    voice: {
      name: 'so-SO-UbaxNeural',
    },
  },
  ['sq-al-anilaneural']: {
    voice: {
      name: 'sq-AL-AnilaNeural',
    },
  },
  ['sq-al-ilirneural']: {
    voice: {
      name: 'sq-AL-IlirNeural',
    },
  },
  ['sr-latn-rs-nicholasneural']: {
    voice: {
      name: 'sr-Latn-RS-NicholasNeural',
    },
  },
  ['sr-latn-rs-sophieneural']: {
    voice: {
      name: 'sr-Latn-RS-SophieNeural',
    },
  },
  ['sr-rs-nicholasneural']: {
    voice: {
      name: 'sr-RS-NicholasNeural',
    },
  },
  ['sr-rs-sophieneural']: {
    voice: {
      name: 'sr-RS-SophieNeural',
    },
  },
  ['su-id-jajangneural']: {
    voice: {
      name: 'su-ID-JajangNeural',
    },
  },
  ['su-id-tutineural']: {
    voice: {
      name: 'su-ID-TutiNeural',
    },
  },
  ['sv-se-hillevineural']: {
    voice: {
      name: 'sv-SE-HilleviNeural',
    },
  },
  ['sv-se-mattiasneural']: {
    voice: {
      name: 'sv-SE-MattiasNeural',
    },
  },
  ['sv-se-sofieneural']: {
    voice: {
      name: 'sv-SE-SofieNeural',
    },
  },
  ['sw-ke-rafikineural']: {
    voice: {
      name: 'sw-KE-RafikiNeural',
    },
  },
  ['sw-ke-zurineural']: {
    voice: {
      name: 'sw-KE-ZuriNeural',
    },
  },
  ['sw-tz-daudineural']: {
    voice: {
      name: 'sw-TZ-DaudiNeural',
    },
  },
  ['sw-tz-rehemaneural']: {
    voice: {
      name: 'sw-TZ-RehemaNeural',
    },
  },
  ['ta-in-pallavineural']: {
    voice: {
      name: 'ta-IN-PallaviNeural',
    },
  },
  ['ta-in-valluvarneural']: {
    voice: {
      name: 'ta-IN-ValluvarNeural',
    },
  },
  ['ta-lk-kumarneural']: {
    voice: {
      name: 'ta-LK-KumarNeural',
    },
  },
  ['ta-lk-saranyaneural']: {
    voice: {
      name: 'ta-LK-SaranyaNeural',
    },
  },
  ['ta-my-kanineural']: {
    voice: {
      name: 'ta-MY-KaniNeural',
    },
  },
  ['ta-my-suryaneural']: {
    voice: {
      name: 'ta-MY-SuryaNeural',
    },
  },
  ['ta-sg-anbuneural']: {
    voice: {
      name: 'ta-SG-AnbuNeural',
    },
  },
  ['ta-sg-venbaneural']: {
    voice: {
      name: 'ta-SG-VenbaNeural',
    },
  },
  ['te-in-mohanneural']: {
    voice: {
      name: 'te-IN-MohanNeural',
    },
  },
  ['te-in-shrutineural']: {
    voice: {
      name: 'te-IN-ShrutiNeural',
    },
  },
  ['th-th-acharaneural']: {
    voice: {
      name: 'th-TH-AcharaNeural',
    },
  },
  ['th-th-niwatneural']: {
    voice: {
      name: 'th-TH-NiwatNeural',
    },
  },
  ['th-th-premwadeeneural']: {
    voice: {
      name: 'th-TH-PremwadeeNeural',
    },
  },
  ['tr-tr-ahmetneural']: {
    voice: {
      name: 'tr-TR-AhmetNeural',
    },
  },
  ['tr-tr-emelneural']: {
    voice: {
      name: 'tr-TR-EmelNeural',
    },
  },
  ['uk-ua-ostapneural']: {
    voice: {
      name: 'uk-UA-OstapNeural',
    },
  },
  ['uk-ua-polinaneural']: {
    voice: {
      name: 'uk-UA-PolinaNeural',
    },
  },
  ['ur-in-gulneural']: {
    voice: {
      name: 'ur-IN-GulNeural',
    },
  },
  ['ur-in-salmanneural']: {
    voice: {
      name: 'ur-IN-SalmanNeural',
    },
  },
  ['ur-pk-asadneural']: {
    voice: {
      name: 'ur-PK-AsadNeural',
    },
  },
  ['ur-pk-uzmaneural']: {
    voice: {
      name: 'ur-PK-UzmaNeural',
    },
  },
  ['uz-uz-madinaneural']: {
    voice: {
      name: 'uz-UZ-MadinaNeural',
    },
  },
  ['uz-uz-sardorneural']: {
    voice: {
      name: 'uz-UZ-SardorNeural',
    },
  },
  ['vi-vn-hoaimyneural']: {
    voice: {
      name: 'vi-VN-HoaiMyNeural',
    },
  },
  ['vi-vn-namminhneural']: {
    voice: {
      name: 'vi-VN-NamMinhNeural',
    },
  },
  ['wuu-cn-xiaotongneural']: {
    voice: {
      name: 'wuu-CN-XiaotongNeural',
    },
  },
  ['wuu-cn-yunzheneural']: {
    voice: {
      name: 'wuu-CN-YunzheNeural',
    },
  },
  ['yue-cn-xiaominneural']: {
    voice: {
      name: 'yue-CN-XiaoMinNeural',
    },
  },
  ['yue-cn-yunsongneural']: {
    voice: {
      name: 'yue-CN-YunSongNeural',
    },
  },
  ['zh-cn-henan-yundengneural']: {
    voice: {
      name: 'zh-CN-henan-YundengNeural',
    },
  },
  ['zh-cn-liaoning-xiaobeineural']: {
    voice: {
      name: 'zh-CN-liaoning-XiaobeiNeural',
    },
  },
  ['zh-cn-shaanxi-xiaonineural']: {
    voice: {
      name: 'zh-CN-shaanxi-XiaoniNeural',
    },
  },
  ['zh-cn-shandong-yunxiangneural']: {
    voice: {
      name: 'zh-CN-shandong-YunxiangNeural',
    },
  },
  ['zh-cn-sichuan-yunxineural']: {
    voice: {
      name: 'zh-CN-sichuan-YunxiNeural',
    },
  },
  ['zh-cn-xiaochenmultilingualneural']: {
    voice: {
      name: 'zh-CN-XiaochenMultilingualNeural',
    },
  },
  ['zh-cn-xiaochenneural']: {
    voice: {
      name: 'zh-CN-XiaochenNeural',
    },
  },
  ['zh-cn-xiaohanneural']: {
    voice: {
      name: 'zh-CN-XiaohanNeural',
    },
  },
  ['zh-cn-xiaomengneural']: {
    voice: {
      name: 'zh-CN-XiaomengNeural',
    },
  },
  ['zh-cn-xiaomoneural']: {
    voice: {
      name: 'zh-CN-XiaomoNeural',
    },
  },
  ['zh-cn-xiaoqiuneural']: {
    voice: {
      name: 'zh-CN-XiaoqiuNeural',
    },
  },
  ['zh-cn-xiaorouneural']: {
    voice: {
      name: 'zh-CN-XiaorouNeural',
    },
  },
  ['zh-cn-xiaoruineural']: {
    voice: {
      name: 'zh-CN-XiaoruiNeural',
    },
  },
  ['zh-cn-xiaoshuangneural']: {
    voice: {
      name: 'zh-CN-XiaoshuangNeural',
    },
  },
  ['zh-cn-xiaoxiaodialectsneural']: {
    voice: {
      name: 'zh-CN-XiaoxiaoDialectsNeural',
    },
  },
  ['zh-cn-xiaoxiaomultilingualneural']: {
    voice: {
      name: 'zh-CN-XiaoxiaoMultilingualNeural',
    },
  },
  ['zh-cn-xiaoxiaoneural']: {
    voice: {
      name: 'zh-CN-XiaoxiaoNeural',
    },
  },
  ['zh-cn-xiaoyanneural']: {
    voice: {
      name: 'zh-CN-XiaoyanNeural',
    },
  },
  ['zh-cn-xiaoyineural']: {
    voice: {
      name: 'zh-CN-XiaoyiNeural',
    },
  },
  ['zh-cn-xiaoyouneural']: {
    voice: {
      name: 'zh-CN-XiaoyouNeural',
    },
  },
  ['zh-cn-xiaoyumultilingualneural']: {
    voice: {
      name: 'zh-CN-XiaoyuMultilingualNeural',
    },
  },
  ['zh-cn-xiaozhenneural']: {
    voice: {
      name: 'zh-CN-XiaozhenNeural',
    },
  },
  ['zh-cn-yunfengneural']: {
    voice: {
      name: 'zh-CN-YunfengNeural',
    },
  },
  ['zh-cn-yunhaoneural']: {
    voice: {
      name: 'zh-CN-YunhaoNeural',
    },
  },
  ['zh-cn-yunjianneural']: {
    voice: {
      name: 'zh-CN-YunjianNeural',
    },
  },
  ['zh-cn-yunjieneural']: {
    voice: {
      name: 'zh-CN-YunjieNeural',
    },
  },
  ['zh-cn-yunxianeural']: {
    voice: {
      name: 'zh-CN-YunxiaNeural',
    },
  },
  ['zh-cn-yunxiaomultilingualneural']: {
    voice: {
      name: 'zh-CN-YunxiaoMultilingualNeural',
    },
  },
  ['zh-cn-yunxineural']: {
    voice: {
      name: 'zh-CN-YunxiNeural',
    },
  },
  ['zh-cn-yunyangneural']: {
    voice: {
      name: 'zh-CN-YunyangNeural',
    },
  },
  ['zh-cn-yunyeneural']: {
    voice: {
      name: 'zh-CN-YunyeNeural',
    },
  },
  ['zh-cn-yunyimultilingualneural']: {
    voice: {
      name: 'zh-CN-YunyiMultilingualNeural',
    },
  },
  ['zh-cn-yunzeneural']: {
    voice: {
      name: 'zh-CN-YunzeNeural',
    },
  },
  ['zh-hk-hiugaaineural']: {
    voice: {
      name: 'zh-HK-HiuGaaiNeural',
    },
  },
  ['zh-hk-hiumaanneural']: {
    voice: {
      name: 'zh-HK-HiuMaanNeural',
    },
  },
  ['zh-hk-wanlungneural']: {
    voice: {
      name: 'zh-HK-WanLungNeural',
    },
  },
  ['zh-tw-hsiaochenneural']: {
    voice: {
      name: 'zh-TW-HsiaoChenNeural',
    },
  },
  ['zh-tw-hsiaoyuneural']: {
    voice: {
      name: 'zh-TW-HsiaoYuNeural',
    },
  },
  ['zh-tw-yunjheneural']: {
    voice: {
      name: 'zh-TW-YunJheNeural',
    },
  },
  ['zu-za-thandoneural']: {
    voice: {
      name: 'zu-ZA-ThandoNeural',
    },
  },
  ['zu-za-thembaneural']: {
    voice: {
      name: 'zu-ZA-ThembaNeural',
    },
  },
};
